### ISSUE TITLE
show the channel thumbnail with search results

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#10]

**Comment by Aarush-Goyal** [comment]
@shriyaMadan I would like to work on this

**Comment by Aarush-Goyal** [comment]
@shriyaMadan I am getting this error :
`Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".
` 
Can you help me with that?

**Comment by Aarush-Goyal** [comment]
@shriyaMadan I have made a pr fixing the issue c-3 added channel thumbnails #14 kindly check it
