### ISSUE TITLE
Add navyBlue Dark Mode Feature

### ISSUE THREAD

**Issue by chait04** [shriyaMadan/Youtube-Dashboard#101]
## 🔎 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/shriyaMadan/Youtube-Dashboard/blob/master/CONTRIBUTING.md)?

It already have dark mode but the blue one will look good

(Please explain why this feature should be implemented and how it would be used.)

**Comment by shriyaMadan** [comment]
Not needed rn, there are better things to do
