### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Vrushti24** [shriyaMadan/Youtube-Dashboard#102]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/shriyaMadan/Youtube-Dashboard/blob/master/CONTRIBUTING.md)?

This project does not contain any license . I think it's important to have license like MIT or any other

**Comment by Vrushti24** [comment]
I can work on this please assign to me

**Comment by shriyaMadan** [comment]
yes you can go ahead with it

**Comment by Vrushti24** [comment]
PR #104 done please check that
