### ISSUE TITLE
Feature of Sign-in to Youtube account

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#13]
Making a Sign-In for Youtube account so that a person can later view personal statistics on the dashboard.

**Comment by Aarush-Goyal** [comment]
You want to add authentication with youtube? Should I do it with passport js?

**Comment by Zircoz** [comment]
Hey @Aarush-Goyal ! 
We aim to provide users analysis of their channel's private stats, for which this app will need their permissions. See [documentation](https://developers.google.com/youtube/v3/guides/authentication) for the same.

**Comment by Aarush-Goyal** [comment]
I have fixed the issue with pr #20 also do contact me for getting a better understanding of the auth flow and Oauth Verification

**Comment by shriyaMadan** [comment]
Good work!
