### ISSUE TITLE
Encourage youtubers by displaying relevant messages 

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#16]
If some channel has 90 subscribers, then a message like "Only 10 more to reach 100!" And adding up with benefits we get after we reach that number. Like in 100 subscribers we can have a custom URL for our channel and live streaming via mobile app.
Also with a small encouraging animation saying "Kudos" and then the next target of maybe 500 subs. 
Join the discussion with me to discuss more on this idea.

**Comment by Sakshi-25** [comment]
Kindly assign some creative task to me. I'm good at it. Can I create logos, stickers etc for this app?

**Comment by Aarush-Goyal** [comment]
@Sakshi-25 Yes I guess a logo would be great

**Comment by shriyaMadan** [comment]
@Sakshi-25 a new issue for the logo is made. You can start working on it and comment there.

**Comment by Rimpi246** [comment]
> If some channel has 90 subscribers, then a message like "Only 10 more to reach 100!" And adding up with benefits we get after we reach that number. Like in 100 subscribers we can have a custom URL for our channel and live streaming via mobile app.
> Also with a small encouraging animation saying "Kudos" and then the next target of maybe 500 subs.
> Join the discussion with me to discuss more on this idea.

Ma'am where to join the discussion?

**Comment by Sakshi-25** [comment]
> @Sakshi-25 Yes I guess a logo would be great

I made logo and commented on the issue for the logo. Kindly see to it so that I can make a PR. Please assign me for logo.

**Comment by Aarush-Goyal** [comment]
I would like to work on this
