### ISSUE TITLE
create a logo for this project

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#17]
Keep the following in mind while making the logo:
-The logo should be designed such that it looks good both in light and dark mode.
-This project is about statistics and data about youtube channels. So the logo should be designed accordingly.

You can discuss more in the discussions session
Ideas are welcomed.

**Comment by Muskan10Mehta** [comment]
Hey! I would like to work on this issue..

**Comment by Vrushti24** [comment]
I would like to contribute in this project please guide me!!

**Comment by shriyaMadan** [comment]
@Muskan10Mehta you can start creating a logo for this project.

**Comment by Sakshi-25** [comment]
@shriyaMadan I was assigned this issue ( when this issue for logo was not created). Please see to this, I've made some logos.

Logo1 : https://www.figma.com/file/wGeErIP3VIQhTYNM2oYwpO/Untitled?node-id=0%3A1
Logo 2 : https://www.figma.com/file/LihUWtUPMceHqo9wqlPWeI/Logo-Youtube-Dashboard?node-id=0%3A1
Logo 3 : https://www.figma.com/file/tKFdlXtySVIH0TbKBIqDqG/Logo1?node-id=0%3A1

**Comment by Muskan10Mehta** [comment]
Hey! I have designed two logo designs for now, please let me know if any changes are required..

![1](https://user-images.githubusercontent.com/69207355/103177966-d167a880-48a4-11eb-8e79-5b3c4cb08a04.png)
![2](https://user-images.githubusercontent.com/69207355/103177968-d298d580-48a4-11eb-990e-60559d58a307.png)
![3](https://user-images.githubusercontent.com/69207355/103177970-d4629900-48a4-11eb-8a81-0f0417231dff.png)
![4](https://user-images.githubusercontent.com/69207355/103177971-d593c600-48a4-11eb-8635-0e0e991108ba.png)

demo in both light and dark mode..

**Comment by Aarush-Goyal** [comment]
@Sakshi-25  The first one looks good but don't you think you should use a better font for the small text

**Comment by Aarush-Goyal** [comment]
https://www.figma.com/file/DSdZ2egARZwgy18mX4nmoM/Untitled?node-id=3%3A0
https://www.figma.com/file/DSdZ2egARZwgy18mX4nmoM/Untitled?node-id=4%3A11

**Comment by Aarush-Goyal** [comment]
https://www.figma.com/file/DSdZ2egARZwgy18mX4nmoM/Untitled?node-id=3%3A0
https://www.figma.com/file/DSdZ2egARZwgy18mX4nmoM/Untitled?node-id=4%3A11
Have a look at these @shriyaMadan @Muskan10Mehta @Sakshi-25

**Comment by Sakshi-25** [comment]
They're good!! we can use these in different parts of websites, like Output buttons, One logo can be used on the login page, one on the main website, like that.
@shriyaMadan Kindly sort this.

**Comment by Muskan10Mehta** [comment]
these are great but dont you think the gears make it look more like its a settings logo?

**Comment by Chetna23-code** [comment]
I would like to contribute to this issue.

**Comment by shriyaMadan** [comment]
@Muskan10Mehta your YTD logo was good, but it's looking old style, try to improve it.

**Comment by Muskan10Mehta** [comment]
sure

**Comment by shriyaMadan** [comment]
@Muskan10Mehta any update?

**Comment by Muskan10Mehta** [comment]
yes
![6](https://user-images.githubusercontent.com/69207355/103338292-e9594b00-4aa3-11eb-8c99-157be8a01062.png)
![8](https://user-images.githubusercontent.com/69207355/103338293-ea8a7800-4aa3-11eb-918c-c6150d2087e0.png)
are these okay?

**Comment by Aarush-Goyal** [comment]
@Muskan10Mehta great work on the logos

**Comment by Muskan10Mehta** [comment]
Thanks!

**Comment by Muskan10Mehta** [comment]
@shriyaMadan any decisions on logo?

**Comment by shriyaMadan** [comment]
Yes your third YTD logo looks good, maybe will suggest changes while using it in UI.

**Comment by Muskan10Mehta** [comment]
okay.. thanks for the oppurtunity

**Comment by shriyaMadan** [comment]
Hey @Muskan10Mehta send a PR of your logo so that it is counted under DWOC.
