### ISSUE TITLE
Having search suggestion

### ISSUE THREAD

**Issue by Rimpi246** [shriyaMadan/Youtube-Dashboard#18]
There is no search suggestion like in the YouTube app itself. So that we don't need to type much

**Comment by pankajkumarbij** [comment]
Hello, I would like to contribute to this issue.

**Comment by Rimpi246** [comment]
Me too...But I don't know what tools will be required

**Comment by shriyaMadan** [comment]
@pankajkumarbij you can start contributing to this issue.

**Comment by shriyaMadan** [comment]
What are you gonna use @pankajkumarbij  for search suggestions?

**Comment by pankajkumarbij** [comment]
> What are you gonna use @pankajkumarbij for search suggestions?

SImple JavaScript and Jquery.

**Comment by Rimpi246** [comment]
@shriyaMadan Allow me too to contribute to this feature

**Comment by shriyaMadan** [comment]
@Rimpi246 what's your idea to work on this issue?

**Comment by Rimpi246** [comment]
I will use javascript ,jQuery and google API

**Comment by Aarush-Goyal** [comment]
@Rimpi246 Don't you think Jquery is a bit old school?

**Comment by shriyaMadan** [comment]
Any progress? @pankajkumarbij

**Comment by pankajkumarbij** [comment]
This issue is solved but now I not able to run the project.
When I run the project it asks for the keys.json file but previously it not asking for keys.json I think you merged some new PR.
Please tell me about the keys.json file  So I can make a PR.

**Comment by pankajkumarbij** [comment]
> Any progress? @pankajkumarbij

I have sent a PR.
Please review it.
