### ISSUE TITLE
Enhance the ui of "/" route page

### ISSUE THREAD

**Issue by Aarush-Goyal** [shriyaMadan/Youtube-Dashboard#21]
The page is actually just having a link to login with YoutTube it would be nice to have a better-looking page

**Comment by Sakshi-25** [comment]
Kindly assign me this issue.

**Comment by Aarush-Goyal** [comment]
Cool you can start working on it @shriyaMadan will soon assign it to you

**Comment by shriyaMadan** [comment]
I am thinking to make a single button on the homepage itself for login.

**Comment by dsnehasish74** [comment]
Can you assign this to me . I would love to contribute

**Comment by shriyaMadan** [comment]
This issue is not needed now, the Login button will be on the homepage itself.
