### ISSUE TITLE
Adding contributing file and update readme

### ISSUE THREAD

**Issue by bhavesh1129** [shriyaMadan/Youtube-Dashboard#23]
Hey @shriyaMadan!
I want to rearrange your existing readme file.
And add contributing.MD file by including all necessary details, guidelines, and to look it better I will add some relevant images and emojis.

Hope you like it.
Thank you!

**Comment by Sloth-Panda** [comment]
Hey, can I help with this issue?

**Comment by shriyaMadan** [comment]
@bhavesh1129 Let me know if you have started work?

**Comment by bhavesh1129** [comment]
Yeah, @shriyaMadan, I had already started my work and it is almost complete.
Also, I'll make the PR soon.

**Comment by shriyaMadan** [comment]
@bhavesh1129 check the linked pull request and my comment

**Comment by Zircoz** [comment]
@shriyaMadan he has basically copy pasted the file with some changes from somewhere else ;---; Even the screenshots are not of this project ;--; So ludicrous.
I suggest removing the labels from his Pull Request and asking him to do another with more careful commits or assign it to someone else. We don't need hacktoberfest2020 all over again ;--; LMK what you think.

**Comment by bhavesh1129** [comment]
> @shriyaMadan he has basically copy-pasted the file with some changes from somewhere else;---; Even the screenshots are not of this project;--; So ludicrous.
> I suggest removing the labels from his Pull Request and asking him to do another with more careful commits or assigning this issue to someone else. We don't need hacktoberfest2020 all over again;--; LMK what you think.

Hey @Zircoz!
I had not copy-pasted all this stuff as I was assigned to update the contributing files of 2,3 projects so by mistake I had added the wrong screenshots and don't compare each and everyone with Hacktoberfest20 without knowing the actual reason.
and sorry for the inconvenience. 
I apologize for that.

**Comment by Zircoz** [comment]
Kewl @bhavesh1129 ,
Thanks for clarifying

**Comment by shriyaMadan** [comment]
@bhavesh1129 your PR has a conflict, kindly resolve it and send a PR again.

**Comment by shriyaMadan** [comment]
Send PR in new branch named "Docs updation" @bhavesh1129

**Comment by shriyaMadan** [comment]
Git pull to save the existing changes before pushing @bhavesh1129

**Comment by shriyaMadan** [comment]
Updation of Readme Still needed, All the Steps of Running this File locally need to be in one single MD file named: "Run on Localhost Guide"
In the Readme file, the link of "Run on Localhost Guide" and "Contributing guide" should be mentioned.
And Remove those steps from the Contributing guide.

**Comment by shriyaMadan** [comment]
Steps including both Creating of Youtube API Key and Oauth should be in one single file.

**Comment by shriyaMadan** [comment]
Who's working on this? I wanna revert Contributing Guide again @bhavesh1129 You copied it from Readme again.

**Comment by shriyaMadan** [comment]
@Sloth-Panda are you willing to add a Contribution Guide?
Make sure that you mention its link in the Readme file also.

**Comment by Sloth-Panda** [comment]
yes yes sure I just forgot to do will do it and let you know soon

**Comment by Sloth-Panda** [comment]
But why have you removed the tags of DWoC ?? Kindly add them. I see there's a 500 error while I am cloning this project. what can I do about that?

**Comment by shriyaMadan** [comment]
I was changing tags, Are you not on discord?

**Comment by shriyaMadan** [comment]
On discord group send your Gmail id.

**Comment by Sloth-Panda** [comment]
Yes I am on discord

**Comment by shriyaMadan** [comment]
@Sloth-Panda updates?

**Comment by Sloth-Panda** [comment]
Hey, it still shows that error 500. Even I can't see the forked repo it says error 500.

**Comment by Sloth-Panda** [comment]
Hey, it seems like you have not yet resolved the issue

**Comment by shriyaMadan** [comment]
Where is your PR @Sloth-Panda? I can't find any contributing Guide. 
Also to resolve your error join the discord group chat for this project.

**Comment by shriyaMadan** [comment]
Also, add the link of the contributing guide to readme @Sloth-Panda so that I can close this issue.
