### ISSUE TITLE
UX design for webpages of this app

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#26]

**Comment by Aarush-Goyal** [comment]
I will like to work on it

**Comment by Aarush-Goyal** [comment]
@shriyaMadan I will make the changes in css will it be fine

**Comment by shriyaMadan** [comment]
first show the design of the webpage you made

**Comment by bhavesh1129** [comment]
I want to work on this issue.

**Comment by Aarush-Goyal** [comment]
![Dashboard](https://user-images.githubusercontent.com/64161383/103725936-b102c100-4ffd-11eb-9a10-d279cac1dbef.png)
@shriyaMadan  I have designed a ui for the dashboard over here

**Comment by shriyaMadan** [comment]
Any discussion on the UI is welcomed folks.

**Comment by SuNiL-Chau** [comment]
Working on it have a look https://www.figma.com/file/hgTxpqB8NmmT5fPvntSJFu/ydb?node-id=0%3A1

**Comment by yashsehgal** [comment]
Can I work on this issue?

**Comment by shriyaMadan** [comment]
yes @yashsehgal we are looking for more ideas. You can propose your design.

**Comment by SuNiL-Chau** [comment]
Hey @shriyaMadan I have updated the design have a look 
https://www.figma.com/file/hgTxpqB8NmmT5fPvntSJFu/ydb?node-id=0%3A1

**Comment by shriyaMadan** [comment]
Good work! @SuNiL-Chau

**Comment by SuNiL-Chau** [comment]
Thank you @shriyaMadan so is there anything you want me to update or we are keeping this final?

**Comment by kanishkaa24** [comment]
@shriyaMadan 
Can I work on this ?

**Comment by shriyaMadan** [comment]
yes you can suggest designs

**Comment by kanishkaa24** [comment]
> yes you can suggest designs

Please assign me.

**Comment by shriyaMadan** [comment]
Check the discord group to see other designs

**Comment by kanishkaa24** [comment]
![My YouTube Dashboard](https://user-images.githubusercontent.com/71253790/104925223-8e40b700-59c4-11eb-8ee0-c44c0ec26f92.png)
Please let me know your views. @shriyaMadan

**Comment by Aarush-Goyal** [comment]
Hey @shriyaMadan  can you close this issue

**Comment by shriyaMadan** [comment]
> ![My YouTube Dashboard](https://user-images.githubusercontent.com/71253790/104925223-8e40b700-59c4-11eb-8ee0-c44c0ec26f92.png)
> Please let me know your views. @shriyaMadan

Good efforts, but this design won't be used, it has No. of dislikes & comments, which are not needed.
Also, the bg of this isn't making any sense according to what our Project is on.
Sorry, @kanishkaa24 this can't be accepted.
