### ISSUE TITLE
Report on relevant features Youtubers get

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#37]
This web app will have a feature where YouTubers will know all features they have access to. And all features they will get access to in the future when they reach a certain number of subscribers.
So, generate a report in google docs mentioning all the features YouTubers get with their range of total number of views/subscribers/likes.

**Comment by sakshikhachane** [comment]
@shriyaMadan I would like to work on this issue. Please assign me this issue.

**Comment by Rimpi246** [comment]
I have made the report.

**Comment by Rimpi246** [comment]
And I would like to work on this issue

**Comment by shriyaMadan** [comment]
send the link of the report to me in discord if it is completed @Rimpi246
