### ISSUE TITLE
Fix search bar

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#39]
The functionality of both search bars should be done by one.
We should be able to search by both Channel name and Channel URL.

**Comment by Sloth-Panda** [comment]
Hey, let  me take this

**Comment by Aarush-Goyal** [comment]
I have started working on it can you assign it to me?

**Comment by Aarush-Goyal** [comment]
The issue has been resolved in #46 @shriyaMadan

**Comment by Aarush-Goyal** [comment]
The issue has been further resolved in #47 @shriyaMadan
