### ISSUE TITLE
MAJOR UPDATE IN README 

### ISSUE THREAD

**Issue by akrish4** [shriyaMadan/Youtube-Dashboard#40]
### Kindly assign me this issue 

![readme1](https://user-images.githubusercontent.com/61831021/103433336-6d7f1000-4c15-11eb-86aa-df0820c75160.PNG)
Similar to the above image , I can add few badges which gives a better look and also in readme file there is no link to the contributing file , so I would like to add that too.

**Comment by shriyaMadan** [comment]
@akrish4 check #23

**Comment by akrish4** [comment]
> @akrish4 check #23

Let me know if you can assign me this iissue , #23 is now about the guide for localhost running and youtube api .. 
But what i have suggested is something else , If you are interested in making your readme file similar to above message , you could assign me this issue to work on this particular feature
