### ISSUE TITLE
Fix bug for heroku

### ISSUE THREAD

**Issue by Zircoz** [shriyaMadan/Youtube-Dashboard#41]

**Comment by Zircoz** [comment]
@shriyaMadan This was sooooooooooooooo easy, i can't believe we missed it. Anyway, which branch here is the latest to push my fixes to?

**Comment by shriyaMadan** [comment]
Obv. Master xD

**Comment by Zircoz** [comment]
Please remove dwoc labels here too @shriyaMadan
