### ISSUE TITLE
Add Contributors.md and Modify README.MD file

### ISSUE THREAD

**Issue by muthuannamalai12** [shriyaMadan/Youtube-Dashboard#44]
Hai,
I would love to add the Contributors.md file to your project in the form of a table and display a link to it in the README.md file. I would also add a link to the Code of Conduct in README.md. If you like I can also add badges for forks, open issue, and pull request in README.md

**Comment by muthuannamalai12** [comment]
I would to work on this issue as a part of DWOC. Kindly assign me this issue

**Comment by Zircoz** [comment]
It is already being worked upon in #23 lol

**Comment by muthuannamalai12** [comment]
> It is already being worked upon in #23 lol 

I have opened an issue for contributors file and not the contributing guide.The issue you have mentioned is for ways for contributing

**Comment by Zircoz** [comment]
Alright, @muthuannamalai12

**Comment by shriyaMadan** [comment]
@muthuannamalai12 No it isn't needed.

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 No it isn't needed.

Ok. Thank you
