### ISSUE TITLE
Add Discord Link in readme, improve Readme

### ISSUE THREAD

**Issue by shriyaMadan** [shriyaMadan/Youtube-Dashboard#73]
## 📚 Documentation

Readme file should become more representable with good emojis and stickers used and add discord group link.

**Comment by tharunc** [comment]
Hello there,
   I would like to work on this Issue as a part of **DWOC**. Can you please assign me this issue.
THANK YOU

**Comment by shriyaMadan** [comment]
Also mention about following templates for issues and the wiki I have added for the PR naming convention.

**Comment by tharunc** [comment]
Can you please share your Discord link ?

**Comment by shriyaMadan** [comment]
Here: https://discord.gg/UhZGbDpw8G

**Comment by shriyaMadan** [comment]
Hey @tharunc what is taking so long? I guess these are small changes.

**Comment by tharunc** [comment]
Sorry for the inconvenience. I will complete the task by today.
THANK YOU

**Comment by Sloth-Panda** [comment]
@shriyaMadan I can happly do it in few minutes can you assign me too.

**Comment by Sloth-Panda** [comment]
pr -> #88
