### ISSUE TITLE
Improvements needed on Home Page

### ISSUE THREAD

**Issue by aniketsingh98571** [shriyaMadan/Youtube-Dashboard#8]
On the home page,  it will be good if you can make the contents align vertically and horizontally center by using flexbox
On the container, div use this.

`Container{
display:flex;
justify-content:center;
align-items:center;
height:80vh
}`

It will look like everything sorted and it is responsive on all devices.If not I can handle it.

**Comment by aniketsingh98571** [comment]
Looking forward to contributing to it as a part of DevScript Winter of Code.

**Comment by shriyaMadan** [comment]
Kindly look for more improvements

**Comment by Aarush-Goyal** [comment]
@aniketsingh98571 @shriyaMadan I guess we can just enhance the UI a little bit also would suggest using React js on the frontend

**Comment by shriyaMadan** [comment]
@aniketsingh98571 @Aarush-Goyal Okay, enhancement is needed in the frontend but take into consideration that this will have the option of viewing own stats and other option of viewing public stats of any channel(which will be done without signing in to Youtube account).

**Comment by shriyaMadan** [comment]
One major improvement needed rn is the name of the channel should be shown when its result is displayed.

**Comment by shriyaMadan** [comment]
@aniketsingh98571 you can start working to improve the home page.

**Comment by aniketsingh98571** [comment]
`Container{ display:flex; justify-content:center; align-items:center; height:80vh }`


@shriyaMadan  Are you talking about this..?

**Comment by shriyaMadan** [comment]
No @aniketsingh98571 these won't do any good.

**Comment by Aarush-Goyal** [comment]
@shriyaMadan I will take care of the dsplay of names on the result page

**Comment by Aarush-Goyal** [comment]
@shriyaMadan I have handled the issue of adding names in pr #15 pls review it

**Comment by shriyaMadan** [comment]
@Aarush-Goyal done and dusted!

**Comment by Sakshi-25** [comment]
Hey, I want to contribute to this project. Kindly assign me some task.
Also, is this done using React / Node?

**Comment by Aarush-Goyal** [comment]
@Sakshi-25 Yes this is made using Node. I will be adding react after some time. If you want to act react you can go forward with that.

**Comment by Satyam1203** [comment]
Can I work on the improvement of homepage? Can do it either in **ReactJS** or just ejs template through node.js. @shriyaMadan @Aarush-Goyal

**Comment by shriyaMadan** [comment]
yes @Satyam1203, you can work on this issue. The project isn't in React yet, it would be using a framework soon.

**Comment by Satyam1203** [comment]
@shriyaMadan, should I make it use ReactJS then?

**Comment by shriyaMadan** [comment]
yes, you may start working on it, me and @Aarush-Goyal will help.

**Comment by Sloth-Panda** [comment]
Hey, I can take this issue. please let me know

**Comment by shriyaMadan** [comment]
@Satyam1203 any updates?

**Comment by Satyam1203** [comment]
I'm on it @shriyaMadan. Most probably would drop a PR by tomorrow end.

**Comment by shriyaMadan** [comment]
> I'm on it @shriyaMadan. Most probably would drop a PR by tomorrow end.

@Satyam1203 updates?
