### ISSUE TITLE
Google hasn't verified this app, 

### ISSUE THREAD

**Issue by manishsamota** [shriyaMadan/Youtube-Dashboard#82]
![BUG](https://user-images.githubusercontent.com/59643473/104316377-648a1a80-5502-11eb-8f52-25cf47cdcbfc.png)

When I try to login into this app using my Gmail then it shows me a message that is :
Google hasn't verified this app. So you can verify it from Google as soon as possible.

**Comment by shriyaMadan** [comment]
@manishsamota check the Readme.md file. I have mentioned there already that app has gone for verification and may take time.
