### ISSUE TITLE
Add Linters

### ISSUE THREAD

**Issue by Zircoz** [shriyaMadan/Youtube-Dashboard#93]
## ✨ Proposal

Add and configure ESLint to make code even for all.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/shriyaMadan/Youtube-Dashboard/blob/master/CONTRIBUTING.md)?
Yes

**Comment by Zircoz** [comment]
@shriyaMadan Please assign it to me, will get it done in some days.

**Comment by shriyaMadan** [comment]
Yes we can use ESlint

**Comment by suchi12j** [comment]
Can i work on this issue?

**Comment by shrutijha16** [comment]
can i work on this issue?

**Comment by shriyaMadan** [comment]
@shrutijha16 yes

> can i work on this issue?
